title: Patrick Buergin
masthead_title: patrickbuergin.com
url: "https://www.patrickbuergin.com"
description: >-
  Thoughts about software engineering, communication, leadership and more.

# Personal information
author:
  name: "Patrick Buergin"
  avatar: "/assets/images/bio-photo.jpg"
  bio: >-
    Working on voice shopping [@amazon](https://www.amazon.jobs/teams/alexa-shopping)
    **::** Views are my own
  linkedin: patrickbuergin
  xing: Patrick_Buergin3
  twitter: patbuergin
  github: patbuergin
social:
  type: Person
  name: Patrick Buergin
  links:
    - "https://www.linkedin.com/in/patrickbuergin/"
    - "https://xing.com/profile/Patrick_Buergin3"
    - "https://twitter.com/patbuergin"

# Layout
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      comments: false
      show_date: true
      read_time: true
      related: false
      share: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.21.0
plugins:
  - jekyll-feed
  - jekyll-include-cache
